name: Dev Release
on: [push, workflow_dispatch]

permissions:
  contents: write

env:
  BUILD_TYPE: Release
jobs:
  dev-release:
    runs-on: windows-latest
    strategy:
      matrix:
        preset: [release-no-debug-msvc, release-no-debug-msvc-xbox]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false
          
      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Get version
        id: get_version
        run: |
          $Version = if ($env:GITHUB_REF -match "refs/tags/(.*)") { $matches[1] } else { "dev" }
          echo "version=$Version" >> $env:GITHUB_OUTPUT

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --preset=build-${{matrix.preset}} 
        env:
          CMAKE_BUILD_TYPE: Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build/build-${{matrix.preset}} --config Release

      - name: Create Package
        run: |
          $Version = "${{ steps.get_version.outputs.version }}"
          $ZipName = if ("${{matrix.preset}}" -like "*xbox") { "starfield2vr-xbox-$Version" } else { "starfield2vr-$Version" }
          mkdir ${{github.workspace}}/package
          mkdir ${{github.workspace}}/symbols
          
          # Copy release files
          Copy-Item "${{github.workspace}}/build/build-${{matrix.preset}}/Release/dxgi.dll" "${{github.workspace}}/package/"
          Copy-Item "${{github.workspace}}/shipping/openvr_api.dll" "${{github.workspace}}/package/"
          Copy-Item "${{github.workspace}}/shipping/openxr_loader.dll" "${{github.workspace}}/package/"
          
          # Copy debug symbols
          Copy-Item "${{github.workspace}}/build/build-${{matrix.preset}}/Release/dxgi.pdb" "${{github.workspace}}/symbols/"
          Copy-Item "${{github.workspace}}/build/build-${{matrix.preset}}/Release/dxgi.dll" "${{github.workspace}}/symbols/"
          
          # Create packages
          7z a "${{github.workspace}}/$ZipName.zip" "${{github.workspace}}/package/*"
          7z a "${{github.workspace}}/$ZipName-symbols.zip" "${{github.workspace}}/symbols/*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: starfield2vr-*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}-${{ steps.get_version.outputs.version }}
          path: ${{github.workspace}}/package/*
          if-no-files-found: error

      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}-${{ steps.get_version.outputs.version }}-symbols
          path: ${{github.workspace}}/symbols/*
          if-no-files-found: error